name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore VacancyManagementApp.sln

      - name: Build solution
        run: dotnet build VacancyManagementApp.sln --configuration Release

      - name: Publish UI project
        run: dotnet publish Presentation/VacancyManagementApp.API/VacancyManagementApp.API.csproj --configuration Release --no-build --output ./publish
